### ISSUE TITLE
Import May 2023 dissertations and masters theses

### ISSUE THREAD

**Issue by bess** [pulibrary/drds_catchall#98] opened 2023-06-20 18:41 UTC
- [ ] Import May 2023 dissertations and masters theses to DataSpace
- [ ] Report back to Lynn when it's done
- [ ] Finish by July 8

Spreadsheet here: 
[ETDAdmin Report May 2023.xlsx](https://github.com/pulibrary/rdss-catchall/files/11805224/ETDAdmin.Report.May.2023.xlsx)

**Comment by kelynch** [comment] 2023-06-20 18:53
Duplicate of https://github.com/pulibrary/dspace-development/issues/764 but there was additional info here; I added it to the dspace-development ticket.

**Closed as completed by kelynch** 2023-06-20 18:53 UTC
